// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EnhancedEbookWebApp.Data;

namespace EnhancedEbookWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200206185726_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EnhancedEbookWebApp.Models.Ebook", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<byte[]>("Content");

                    b.Property<long>("Size");

                    b.Property<string>("Title");

                    b.Property<string>("UntrustedName");

                    b.Property<DateTime>("UploadDT");

                    b.HasKey("ID");

                    b.ToTable("Ebook");
                });
#pragma warning restore 612, 618
        }
    }
}
